#ifndef __BSP_IO_DEFINE_H
#define __BSP_IO_DEFINE_H

#include "main.h"

//adc
#define BSP_ADC          ADC0
#define BSP_ADC_RCU      RCU_ADC0
#define BSP_ADC_DMA_RCU  RCU_DMA1
#define BSP_ADC_DMA      DMA1
#define BSP_ADC_DMA_CH   DMA_CH0

#define BSP_JSK_X_PORT   GPIOA
#define BSP_JSK_Y_PORT   GPIOC
#define BSP_BAT_PORT     GPIOB

#define BSP_JSK_X_PIN    GPIO_PIN_1
#define BSP_JSK_Y_PIN    GPIO_PIN_1
#define BSP_BAT_PIN      GPIO_PIN_1

#define BSP_JSK_X_ADC_CH ADC_CHANNEL_1
#define BSP_JSK_Y_ADC_CH ADC_CHANNEL_11
#define BSP_BAT_ADC_CH   ADC_CHANNEL_9
#define BSP_TEMP_ADC_CH  ADC_CHANNEL_16
#define BSP_VREF_ADC_CH  ADC_CHANNEL_17

// led key
#define BSP_LED1_PORT  GPIOE
#define BSP_LED2_PORT  GPIOD
#define BSP_LED3_PORT  GPIOG
#define BSP_LED4_PORT  GPIOA
#define BSP_KEY_L_PORT GPIOA
#define BSP_KEY_A_PORT GPIOG
#define BSP_KEY_B_PORT GPIOB
#define BSP_KEY_R_PORT GPIOB

#define BSP_LED1_PIN   GPIO_PIN_3
#define BSP_LED2_PIN   GPIO_PIN_7
#define BSP_LED3_PIN   GPIO_PIN_3
#define BSP_LED4_PIN   GPIO_PIN_5
#define BSP_KEY_L_PIN  GPIO_PIN_0
#define BSP_KEY_A_PIN  GPIO_PIN_9
#define BSP_KEY_B_PIN  GPIO_PIN_15
#define BSP_KEY_R_PIN  GPIO_PIN_2

// timer
#define BSP_TIMER_TICK        TIMER6
#define BSP_TIMER_TICK_RCU    RCU_TIMER6
#define BSP_TIMER_TICK_IRQ    TIMER6_IRQn // 定时器中断
#define BSP_TickTimer_Handler TIMER6_IRQHandler

// timer lcd
#define BSP_PWM_LCD_TIMER     TIMER2
#define BSP_PWM_LCD_TIMER_RCU RCU_TIMER2
#define BSP_PWM_LCD_BLK_CH    TIMER_CH_1
#define BSP_PWM_LCD_BLK_PORT  GPIOA
#define BSP_PWM_LCD_BLK_PIN   GPIO_PIN_7

// motor
#define BSP_PWM_MOTOR_TIMER     TIMER1
#define BSP_PWM_MOTOR_TIMER_RCU RCU_TIMER1
#define BSP_PWM_MOTOR_CH        TIMER_CH_2
#define BSP_PWM_MOTOR_PORT      GPIOA
#define BSP_PWM_MOTOR_PIN       GPIO_PIN_2

// iic
#define BSP_EEPROM_IIC          I2C0
#define BSP_EEPROM_IIC_RCU      RCU_I2C0

#define BSP_IIC_EEPROM_SCL_PORT GPIOB
#define BSP_IIC_EEPROM_SCL_PIN  GPIO_PIN_6

#define BSP_IIC_EEPROM_SDA_PORT GPIOB
#define BSP_IIC_EEPROM_SDA_PIN  GPIO_PIN_7

// spi w25qxx
#define BSP_FLASH_SPI         SPI4
#define BSP_SPI_FLASH_RCU     RCU_SPI4

#define BSP_SPI_FLASH_DI_PORT GPIOF
#define BSP_SPI_FLASH_DI_PIN  GPIO_PIN_9

#define BSP_SPI_FLASH_DO_PORT GPIOF
#define BSP_SPI_FLASH_DO_PIN  GPIO_PIN_8

#define BSP_SPI_FLASH_CK_PORT GPIOF
#define BSP_SPI_FLASH_CK_PIN  GPIO_PIN_7

#define BSP_SPI_FLASH_CS_PORT GPIOF
#define BSP_SPI_FLASH_CS_PIN  GPIO_PIN_6

// spi lcd
#define BSP_LCD_SPI            SPI4
#define BSP_SPI_FLASH_RCU      RCU_SPI4

#define BSP_SPI_LCD_DC_PORT    GPIOA
#define BSP_SPI_LCD_DC_PIN     GPIO_PIN_6

#define BSP_SPI_LCD_CK_PORT    GPIOF
#define BSP_SPI_LCD_CK_PIN     GPIO_PIN_7

#define BSP_SPI_LCD_MOSI_PORT  GPIOF
#define BSP_SPI_LCD_MOSI_PIN   GPIO_PIN_9

#define BSP_SPI_LCD_CS_PORT    GPIOA
#define BSP_SPI_LCD_CS_PIN     GPIO_PIN_4

#define BSP_SPI_LCD_RESET_PORT GPIOF
#define BSP_SPI_LCD_RESET_PIN  GPIO_PIN_10

// usart
#define BSP_USART           USART0
#define BSP_USART_DMA       DMA1

#define BSP_USART_RCU       RCU_USART0
#define BSP_USART_DMA_RCU   RCU_DMA1
#define BSP_USART_DMA_TX_CH DMA_CH7
#define BSP_USART_DMA_RX_CH DMA_CH5

#define BSP_USART_IRQ       USART0_IRQn
#define BSP_USART_Handler   USART0_IRQHandler

#define BSP_USART_TX_PORT   GPIOA
#define BSP_USART_RX_PORT   GPIOA
#define BSP_USART_TX_PIN    GPIO_PIN_9
#define BSP_USART_RX_PIN    GPIO_PIN_10

// exmc
// exmc addr
#define BSP_SDRAM_EXMC          EXMC_SDRAM_DEVICE0
#define BSP_SDRAM_EXMC_RCU      RCU_EXMC

#define BSP_EXMC_SDRAM_A0_PORT  GPIOF
#define BSP_EXMC_SDRAM_A0_PIN   GPIO_PIN_0

#define BSP_EXMC_SDRAM_A1_PORT  GPIOF
#define BSP_EXMC_SDRAM_A1_PIN   GPIO_PIN_1

#define BSP_EXMC_SDRAM_A2_PORT  GPIOF
#define BSP_EXMC_SDRAM_A2_PIN   GPIO_PIN_2

#define BSP_EXMC_SDRAM_A3_PORT  GPIOF
#define BSP_EXMC_SDRAM_A3_PIN   GPIO_PIN_3

#define BSP_EXMC_SDRAM_A4_PORT  GPIOF
#define BSP_EXMC_SDRAM_A4_PIN   GPIO_PIN_4

#define BSP_EXMC_SDRAM_A5_PORT  GPIOF
#define BSP_EXMC_SDRAM_A5_PIN   GPIO_PIN_5

#define BSP_EXMC_SDRAM_A6_PORT  GPIOF
#define BSP_EXMC_SDRAM_A6_PIN   GPIO_PIN_12

#define BSP_EXMC_SDRAM_A7_PORT  GPIOF
#define BSP_EXMC_SDRAM_A7_PIN   GPIO_PIN_13

#define BSP_EXMC_SDRAM_A8_PORT  GPIOF
#define BSP_EXMC_SDRAM_A8_PIN   GPIO_PIN_14

#define BSP_EXMC_SDRAM_A9_PORT  GPIOF
#define BSP_EXMC_SDRAM_A9_PIN   GPIO_PIN_15

#define BSP_EXMC_SDRAM_A10_PORT GPIOG
#define BSP_EXMC_SDRAM_A10_PIN  GPIO_PIN_0

#define BSP_EXMC_SDRAM_A11_PORT GPIOG
#define BSP_EXMC_SDRAM_A11_PIN  GPIO_PIN_1

#define BSP_EXMC_SDRAM_A12_PORT GPIOG
#define BSP_EXMC_SDRAM_A12_PIN  GPIO_PIN_2

// exmc data
#define BSP_EXMC_SDRAM_D0_PORT  GPIOD
#define BSP_EXMC_SDRAM_D0_PIN   GPIO_PIN_14

#define BSP_EXMC_SDRAM_D1_PORT  GPIOD
#define BSP_EXMC_SDRAM_D1_PIN   GPIO_PIN_15

#define BSP_EXMC_SDRAM_D2_PORT  GPIOD
#define BSP_EXMC_SDRAM_D2_PIN   GPIO_PIN_0

#define BSP_EXMC_SDRAM_D3_PORT  GPIOD
#define BSP_EXMC_SDRAM_D3_PIN   GPIO_PIN_1

#define BSP_EXMC_SDRAM_D4_PORT  GPIOE
#define BSP_EXMC_SDRAM_D4_PIN   GPIO_PIN_7

#define BSP_EXMC_SDRAM_D5_PORT  GPIOE
#define BSP_EXMC_SDRAM_D5_PIN   GPIO_PIN_8

#define BSP_EXMC_SDRAM_D6_PORT  GPIOE
#define BSP_EXMC_SDRAM_D6_PIN   GPIO_PIN_9

#define BSP_EXMC_SDRAM_D7_PORT  GPIOE
#define BSP_EXMC_SDRAM_D7_PIN   GPIO_PIN_10

#define BSP_EXMC_SDRAM_D8_PORT  GPIOE
#define BSP_EXMC_SDRAM_D8_PIN   GPIO_PIN_11

#define BSP_EXMC_SDRAM_D9_PORT  GPIOE
#define BSP_EXMC_SDRAM_D9_PIN   GPIO_PIN_12

#define BSP_EXMC_SDRAM_D10_PORT GPIOE
#define BSP_EXMC_SDRAM_D10_PIN  GPIO_PIN_13

#define BSP_EXMC_SDRAM_D11_PORT GPIOE
#define BSP_EXMC_SDRAM_D11_PIN  GPIO_PIN_14

#define BSP_EXMC_SDRAM_D12_PORT GPIOE
#define BSP_EXMC_SDRAM_D12_PIN  GPIO_PIN_15

#define BSP_EXMC_SDRAM_D13_PORT GPIOD
#define BSP_EXMC_SDRAM_D13_PIN  GPIO_PIN_8

#define BSP_EXMC_SDRAM_D14_PORT GPIOD
#define BSP_EXMC_SDRAM_D14_PIN  GPIO_PIN_9

#define BSP_EXMC_SDRAM_D15_PORT GPIOD
#define BSP_EXMC_SDRAM_D15_PIN  GPIO_PIN_10

// exmc other
#define BSP_EXMC_SDRAM_NBL0_PORT GPIOE // 低字节控制
#define BSP_EXMC_SDRAM_NBL0_PIN  GPIO_PIN_0

#define BSP_EXMC_SDRAM_NBL1_PORT GPIOE // 高字节控制
#define BSP_EXMC_SDRAM_NBL1_PIN  GPIO_PIN_1

#define BSP_EXMC_SDRAM_CEK0_PORT GPIOC // 时钟使能
#define BSP_EXMC_SDRAM_CEK0_PIN  GPIO_PIN_3

#define BSP_EXMC_SDRAM_BA0_PORT  GPIOG // bank 地址 A0
#define BSP_EXMC_SDRAM_BA0_PIN   GPIO_PIN_4

#define BSP_EXMC_SDRAM_BA1_PORT  GPIOG // bank 地址 A1
#define BSP_EXMC_SDRAM_BA1_PIN   GPIO_PIN_5

#define BSP_EXMC_SDRAM_CLK_PORT  GPIOG // 时钟信号线
#define BSP_EXMC_SDRAM_CLK_PIN   GPIO_PIN_8

#define BSP_EXMC_SDRAM_NCAS_PORT GPIOG // 列地址选通 低电平有效
#define BSP_FMSC_SDR_NCAS_PIN    GPIO_PIN_15

#define BSP_EXMC_SDRAM_NRAS_PORT GPIOF // 行地址选通 低电平有效
#define BSP_EXMC_SDRAM_NRAS_PIN  GPIO_PIN_11

#define BSP_EXMC_SDRAM_NEO_PORT  GPIOC // 输出使能 低电平有效
#define BSP_EXMC_SDRAM_NEO_PIN   GPIO_PIN_2

#define BSP_EXMC_SDRAM_NWE_PORT  GPIOC // 写使能 低电平有效
#define BSP_EXMC_SDRAM_NWE_PIN   GPIO_PIN_0

// dac
#define BSP_AUDIO_DAC               DAC0
#define BSP_AUDIO_DAC_RCU           RCU_DAC
#define BSP_DAC_AUDIO_OUT           DAC_OUT1

#define BSP_AUDIO_TIMER             TIMER7
#define BSP_AUDIO_TIMER_RCU         RCU_TIMER7
#define BSP_AUDIO_TIMER_IRQ         TIMER7_UP_TIMER12_IRQn
#define BSP_AUDIO_TIMER_TRG_Handler TIMER7_UP_TIMER12_IRQHandler

#define BSP_AUDIO_DMA               DMA0
#define BSP_AUDIO_DMA_RCU           RCU_DMA0
#define BSP_AUDIO_DMA_CH            DMA_CH6
#define BSP_AUDIO_DMA_IRQ           DMA0_Channel6_IRQn
#define BSP_AUDIO_Finish_Handler    DMA0_Channel6_IRQHandler

#define BSP_DAC_AUDIO_OUT_PORT      GPIOA
#define BSP_DAC_AUDIO_OUT_PIN       GPIO_PIN_5

// SDIO
#define BSP_SDIO             SDIO
#define BSP_SDIO_RCU         RCU_SDIO
#define BSP_SDIO_IRQ         SDIO_IRQn
#define BSP_SDIO_IRQ_Handler SDIO_IRQHandler

#define BSP_SDIO_DMA         DMA1
#define BSP_SDIO_DMA_RCU     RCU_DMA1
#define BSP_SDIO_DMA_CH      DMA_CH3

#define BSP_SDIO_D0_PORT     GPIOC
#define BSP_SDIO_D0_PIN      GPIO_PIN_8

#define BSP_SDIO_D1_PORT     GPIOC
#define BSP_SDIO_D1_PIN      GPIO_PIN_9

#define BSP_SDIO_D2_PORT     GPIOC
#define BSP_SDIO_D2_PIN      GPIO_PIN_10

#define BSP_SDIO_D3_PORT     GPIOC
#define BSP_SDIO_D3_PIN      GPIO_PIN_11

#define BSP_SDIO_CLK_PORT    GPIOC
#define BSP_SDIO_CLK_PIN     GPIO_PIN_12

#define BSP_SDIO_CMD_PORT    GPIOD
#define BSP_SDIO_CMD_PIN     GPIO_PIN_2

// Debug
#define BSP_DEBUG_TIMER     TIMER4
#define BSP_DEBUG_TIMER_RCU RCU_TIMER4

#endif /* __BSP_IO_DEFINE_H */
